env:
  browser: true
  es2021: true
extends:
  - xo
  - plugin:react/recommended
  - plugin:prettier
overrides:
  - extends:
      - xo-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: {}
